// Scans public/panos/ (360° equirectangular) and public/photos/ (plain HD)
// for images, reads GPS + capture date from their metadata (macOS Spotlight),
// generates missing thumbnails with sips, and writes src/data/manifest.ts.
//
//   node scripts/sync-media.mjs
//
// Images without GPS coordinates are reported and skipped by the site.

import { execFileSync } from 'node:child_process'
import { mkdirSync, readdirSync, existsSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const IMAGE_RE = /\.(jpe?g|png|webp)$/i

function readMeta(path) {
  // key = value lines; mdls does not honor argument order with -raw
  const out = execFileSync(
    'mdls',
    [
      '-name', 'kMDItemLatitude',
      '-name', 'kMDItemLongitude',
      '-name', 'kMDItemContentCreationDate',
      path,
    ],
    { encoding: 'utf8' },
  )
  const fields = {}
  for (const line of out.split('\n')) {
    const m = line.match(/^(kMDItem\w+)\s*=\s*(.+)$/)
    if (m) fields[m[1]] = m[2].replace(/^"|"$/g, '').trim()
  }
  const num = (v) => (v && v !== '(null)' ? Number(v) : null)
  const date = fields.kMDItemContentCreationDate
  return {
    lat: num(fields.kMDItemLatitude),
    lng: num(fields.kMDItemLongitude),
    date: date && date !== '(null)' ? date.slice(0, 7) : '',
  }
}

function scan(dirName) {
  const dir = join(root, 'public', dirName)
  const thumbDir = join(dir, 'thumbs')
  if (!existsSync(dir)) return []
  mkdirSync(thumbDir, { recursive: true })

  const microDir = join(thumbDir, 'micro')
  mkdirSync(microDir, { recursive: true })

  const entries = []
  for (const file of readdirSync(dir).sort()) {
    if (!IMAGE_RE.test(file)) continue
    const full = join(dir, file)
    const thumb = join(thumbDir, file)
    const micro = join(microDir, file)
    if (!existsSync(thumb)) {
      execFileSync('sips', [
        '--resampleHeightWidthMax', '480',
        '-s', 'format', 'jpeg',
        full,
        '--out', thumb,
      ])
    }
    if (!existsSync(micro)) {
      // tiny version used inside the map markers
      execFileSync('sips', [
        '--resampleHeightWidthMax', '128',
        '-s', 'format', 'jpeg',
        thumb,
        '--out', micro,
      ])
    }
    const meta = readMeta(full)
    if (meta.lat == null || meta.lng == null) {
      console.warn(`⚠ no GPS in ${dirName}/${file} — it will not appear on the map`)
    }
    entries.push({ file, ...meta })
    console.log(`✓ ${dirName}/${file} (${meta.lat?.toFixed(3)}, ${meta.lng?.toFixed(3)}) ${meta.date}`)
  }
  return entries
}

const panos = scan('panos')
const photos = scan('photos')

const banner =
  '// AUTO-GENERATED by scripts/sync-media.mjs — run it again after adding images.\n'
const body = `${banner}
export interface RawMedia {
  file: string
  lat: number | null
  lng: number | null
  /** YYYY-MM */
  date: string
}

export const rawPanos: RawMedia[] = ${JSON.stringify(panos, null, 2)}

export const rawPhotos: RawMedia[] = ${JSON.stringify(photos, null, 2)}
`
writeFileSync(join(root, 'src', 'data', 'manifest.ts'), body)
console.log(`\nWrote src/data/manifest.ts — ${panos.length} panoramas, ${photos.length} photos`)
